# Configuração de Financiamento para Visual Studio & Security
# Mantido por Kovaliosky DeV

github: [VisualStudioAndSecurity] # Seu usuário do GitHub para receber Sponsors
patreon: kovalioskydev # Caso queira criar um canal de assinaturas para seus sinais de trading
ko_fi: kovaliosky # Ótimo para "cafés" rápidos por dicas de segurança
custom: ['https://visualstudioandsecurity.com.br/contato'] # Link direto para o seu portal
